### ISSUE TITLE
Feature Request - Font control.

### ISSUE THREAD

**Issue by ulziibat-n** [presscodes/kirki#2463] opened 2022-02-14 08:50 UTC
Hello! 
First, thanks again for Kirki. I always use this plugin on my projects.
I have an idea for the new Kirki control. If will create a new "Font Control," it would be super.

**Why "Font Control" is super?**
We have a "typography control," and it has rich options. But "typography control" has one issue. Its multiple variants.
When I use typography control, it comes with only one variant, and Kirki also has the `$force_load_all_variants = true;` setting, but it imports all variants. 

If Kirki has "Font Control," developers can quickly create font settings with multiple variants and use fonts and variants on their projects.

The idea is "Font Control" has two dropdowns. The first one is the "Font Family" dropdown (Same with "Typography Control"), the second one is the "Font Variants" multi-select dropdown based on the font family.

What do you think?

Thanks. 👍

**Comment by JiveDig** [comment] 2022-02-14 15:00
This is a duplicate of a few other issues requesting a solution to multiple font weights. https://github.com/kirki-framework/kirki/issues/2019, https://github.com/kirki-framework/kirki/issues/1946, https://github.com/kirki-framework/kirki/issues/2276, https://github.com/kirki-framework/kirki/issues/2327.

I agree that a solution to this would be welcomed. Many of us are using filters to manually add extra variants for bold/italic and different weights.

**Comment by mapsteps** [comment] 2022-02-15 10:31
I agree. There needs to be a solution for this but I don't think a seperate control will be it. A multiselect field would make sense to actually load more variants though it's impossible to then dynamically create the CSS using the `output` argument as Kirki doesn't know which variant to use.

A filter would be handy where you pass all variants you would always want to be loaded if they exist.

I'm closing this for now as it's a duplicate. This is definitely in the back of our minds but there just doesn't seem to be a perfect solution for this.

**Closed as completed by mapsteps** 2022-02-15 10:31 UTC
