### ISSUE TITLE
Website crashed after uptade to 4.0.3.

### ISSUE THREAD

**Issue by meierkamer** [presscodes/kirki#2421] opened 2021-12-30 17:09 UTC
### Issue description:
Website crashed after update to 4.0.3.

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 3 der Datei /home/beatri4/www/distisuisse.ch/wp-content/plugins/codeless-builder/include/core/kirki-setup/codeless_custom_section.php verursacht. Fehlermeldung: Uncaught Error: Class 'WP_Customize_Section' not found in /home/beatri4/www/distisuisse.ch/wp-content/plugins/codeless-builder/include/core/kirki-setup/codeless_custom_section.php:3
Stack trace:
#0 /home/beatri4/www/distisuisse.ch/wp-content/plugins/codeless-builder/include/core/cl-kirki-setup.php(74): require_once()
#1 /home/beatri4/www/distisuisse.ch/wp-includes/class-wp-hook.php(303): Cl_Kirki_Setup->load_custom_section(Array)
#2 /home/beatri4/www/distisuisse.ch/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#3 /home/beatri4/www/distisuisse.ch/wp-content/plugins/kirki/packages/kirki-framework/compatibility/src/deprecated/filters.php(13): apply_filters('kirki/section_t...', Array)
#4 /home/beatri4/www/distisuisse.ch/wp-includes/class-wp-hook.php(303): Kirki\Compatibility\Deprecated->{closure}(Array)
#5 /home/beatri4/www/distisuisse.ch/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#6 /home/beatri4/www/distisuisse.ch/wp-content/plugins/kirki/packages/kirki-framework/modu

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by mapsteps** [comment] 2021-12-30 17:42
It seems like Codeless builder is not compatible with Kirki 4. I'm reaching out to them now.

**Comment by mapsteps** [comment] 2021-12-30 17:45
From what I can tell, the Codeless Page Builder hasn't received any updates for over 2 years - https://wordpress.org/plugins/codeless-page-builder/

**Comment by willsheldon** [comment] 2021-12-30 17:58
We have the same issue, but are not using codeless:
`[Thu Dec 30 17:25:42.952583 2021] [php7:error] [pid 321486] [client 10.244.0.225:55726] PHP Fatal error:  Uncaught Error: Class '\\Kirki\\Field\\CSS\\ReactColorful' not found in /var/www/html/wp-content/plugins/k │
│ irki/packages/kirki-framework/module-css/src/CSS/Generator.php:170\nStack trace:\n#0 /var/www/html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\\Module\\CSS\\Generator::css │
│ (Array)\n#1 /var/www/html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\\Module\\CSS::loop_controls('stratus_theme')\n#2 /var/www/html/wp-content/plugins/kirki/packages/kirk │
│ i-framework/module-css/src/CSS.php(179): Kirki\\Module\\CSS->print_styles()\n#3 /var/www/html/wp-includes/class-wp-hook.php(303): Kirki\\Module\\CSS->print_styles_inline('')\n#4 /var/www/html/wp-includes/class-wp │
│ -hook.php(327): WP_Hook->apply_filters(NULL, Array)\n#5 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)\n#6 /var/www/html/wp-includes/general-template.php(3015): do_action('wp_head')\n#7 /var │
│ /www/html/wp-content/themes/stratusx/templates/head.php(10): wp_head()\n#8 /var/www/html/wp-i in /var/www/html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170, refer │`

**Comment by mapsteps** [comment] 2021-12-30 18:01
@willsheldon, are you running version 4.0.3? This was reported previously and should now be fixed.

**Comment by willsheldon** [comment] 2021-12-30 18:05
Hmm, I'm not sure. wp-admin/plugins.php page reports "Version 4.0" but clicking "view details" gives "Version: 3.1.9". I guess this issue is unrelated to this thread either way. Sorry!

**Comment by mapsteps** [comment] 2021-12-30 18:06
No worries :) You can try to download & install the very latest version manually to check if it makes any difference - https://wordpress.org/plugins/kirki/

**Comment by willsheldon** [comment] 2021-12-30 18:18
Confirmed, a manual update to 4.0.3 (latest from https://wordpress.org/plugins/kirki/) resolved the issue.

**Comment by moetimolateli77** [comment] 2021-12-30 21:47
Hi, samething with me also, I have upadated to 4.0.3. I have lost a search bar on the hearder,payment gateway pictures and recently viewed products have also disappeared from the footer. When I disable the plugin, the search bar from the header comes back but the footer still remains a problem. I use Martfury theme.

**Comment by mapsteps** [comment] 2021-12-30 22:00
@moetimolateli77, can you please reach out to the original developers of the theme & check if this is something they can look into on their end? The probably haven't tested their theme with Kirki 4 during the beta phase.

**Comment by moetimolateli77** [comment] 2021-12-30 22:44
I will do so. Thank you.

**Comment by Gnodesign** [comment] 2021-12-30 23:06
This is quite a bomb drop before New Years...

All the default values show as 'null' no matter if it's done natively or in a custom way, unless you change the value and save it. Please look into this!

**Comment by mapsteps** [comment] 2021-12-30 23:26
@Gnodesign, what theme are you using? Can you also please try and get the original theme dev's involved in this? Do you get any errors when testing Kirki 4 with debug mode turned on (https://wp-pagebuilderframework.com/docs/debugging/)?

Any additional information would be helpful.

**Comment by Gnodesign** [comment] 2021-12-30 23:35
@MapSteps I am a theme dev and this issue happens throughout all of my themes. The default values of the added fields show as 'null' and do not present the actual **default** value which causes errors on my code. I could run a check to avoid these error but still the default values should work the same just as is 3.1.9 in order for the fields to actually work.

**Comment by mapsteps** [comment] 2021-12-30 23:39
That's really strange, all defaults are working fine on our end. Can you please just quickly create a new issue so we don't mix things up here too much? That would be awesome. If you can think of anything custom you might have done, for instance to extend Kirki, please mention it there. I'm also happy to look into the theme itself.

**Comment by moetimolateli77** [comment] 2021-12-30 23:57
> @moetimolateli77, can you please reach out to the original developers of the theme & check if this is something they can look into on their end? The probably haven't tested their theme with Kirki 4 during the beta phase.

Looks like I can't get hold of the dev guys.  So does that mean there isn't anything you can do on you side?

**Comment by MapSteps** [comment] 2021-12-31 00:28
@moetimolateli77, we don't have access to the theme. Can you please send us a dropbox/google drive link to connect@mapsteps.com? Thank you!

**Comment by Gnodesign** [comment] 2021-12-31 01:01
@MapSteps Thank you for getting back to me. Will do so!

**Comment by mapsteps** [comment] 2021-12-31 13:31
I'm closing this for now as the chaps over at Codeless said they're going to tackle this on their end.

**Closed as completed by mapsteps** 2021-12-31 13:31 UTC
