### ISSUE TITLE
[Error] 'toggleClass' 

### ISSUE THREAD

**Issue by hainguyenhd** [presscodes/kirki#2424] opened 2021-12-31 02:12 UTC
Here is an example: 
I use this code in php to add class to an element
`$modal_class = get_theme_mod('modal_style', 'open-right');`
in the kirki config code:
```
Kirki::add_field('wooler_config', [
        'type' => 'radio',
        'settings' => 'modal_style',
        'label' => esc_html__('Modal Style'),
        'section' => 'modal_section',
        'default' => 'open-right',
        'priority' => 10,
        'choices' => [
            'open-left' => esc_html__('Left'),
            'open-right' => esc_html__('Right'),
        ],
        'transport' => 'postMessage',
        'js_vars' => array(
            array(
                'element' => '.modal',
                'function' => 'toggleClass',
                'class' => 'open-left',
                'value' => 'open-left',
            ),
            array(
                'element' => '.modal',
                'function' => 'toggleClass',
                'class' => 'open-right',
                'value' => 'open-right',
            ),
        ),
    ]);
```
Result: class 'open-right' was removed because it was added by php before.
This problem does not appear in version 3

**Comment by mapsteps** [comment] 2021-12-31 02:15
Hey @hainguyenhd,

what do you mean by:

> class 'open-right' was removed because it was added by php before

From what I can see, you are simply getting the theme mod value and pass a default, so if no different value was saved in the customizer, it should return `open-right`.

**Comment by hainguyenhd** [comment] 2021-12-31 02:23
Here is my php code: 
```
<?php
$modal_class = get_theme_mod('modal_style', 'open-right');
?>
<div class="modal <?php echo esc_attr($modal_class); ?>">

</div>
```
with the above code the 'class' would be:  'modal open-right'
But when I open Customizer mode it seems that 'toggleClass' js_vars has removed 'open-right' by your code

```
if ( value === output.value && ! jQuery( output.element ).hasClass( output.class ) ) {
	jQuery( output.element ).addClass( output.class );
} else {
	jQuery( output.element ).removeClass( output.class );
}
```

**Comment by mapsteps** [comment] 2021-12-31 15:05
Tested and confirmed. Marking as a bug. The default state should not be removed, thoguh the code you shared is the same in Kirki 3. We now have to check for what's different.

**Comment by contactjavas** [comment] 2022-01-03 09:24
Hi @hainguyenhd , we have found the problem and are able to fix it.

Please update it manually since this is not available yet in WordPress release.
Here is the download link: [v4.0.5](https://github.com/kirki-framework/kirki/files/7801143/kirki.zip)

I've tested this in my side. Please let us know if `v4.0.5` fixes your issue.
Thanks!

**Comment by hainguyenhd** [comment] 2022-01-03 14:53
Thank you!

**Closed as completed** 2022-01-03 18:28 UTC
Labels: bug
