### ISSUE TITLE
Repeater issue: Tooltips are repeated for each option if parent option has tooltip

### ISSUE THREAD

**Issue by AlxMedia** [presscodes/kirki#2445] opened 2022-01-24 17:19 UTC
### Issue description:
Green arrow shows where it should appear, red where it shouldnt: https://i.imgur.com/SSU27FJ.png

### Version used:
4.0.16

**Comment by contactjavas** [comment] 2022-01-24 20:34
Thanks for letting us know this issue, @AlxMedia :)
This is fixed now in `v4.0.18`. Download link: [v4.0.18](https://github.com/kirki-framework/kirki/files/7928690/kirki.zip)

Let us know if this fixes the issue on your side :)
Thanks!

**Comment by AlxMedia** [comment] 2022-01-25 09:09
Works perfectly well now, thanks @contactjavas! :)

There is a minor thing with positioning of the tooltip-bubble, but yeah, not a big issue: https://i.imgur.com/hMUjOwp.png

**Comment by contactjavas** [comment] 2022-01-25 10:35
Is it the arrow, @AlxMedia ? I think we don't add any arrow for the bubble 🤔

**Comment by AlxMedia** [comment] 2022-01-25 10:37
Yea, good idea @contactjavas - would look better without the arrow, I agree.

**Comment by mapsteps** [comment] 2022-01-25 11:06
I wonder where this is coming from. We've discussed the other day wether to add a tooltip indicator arrow or not and decided not to. So I wonder where this is coming from in your screenshot @AlxMedia

**Comment by AlxMedia** [comment] 2022-01-25 13:56
Hmm, strange - so no arrow is supposed to show up - yet it does? I have just added text within a 'tooltip' for the repeater... so the round (?) opens the tooltip, and the rest is shown on the screenshot...

**Comment by mapsteps** [comment] 2022-01-25 15:05
@contactjavas, may this be related to the repeater? Can you pls try and replicate this?

**Comment by AlxMedia** [comment] 2022-01-25 15:17
@contactjavas if you want to try the issue, download https://alx.media/themes/incolor/ and replace the /functions/kirki/ folder with the latest kirki. Then go to Customize > Theme Options > Social Links > (?)-button

Here is the code used: https://github.com/AlxMedia/incolor/blob/master/functions/theme-options.php#L561

**Comment by contactjavas** [comment] 2022-01-25 16:25
Hi @AlxMedia , you're right. There was un-used styles which I missed to delete.
The issue is fixed here and it will be shipped to the next patch / minor release. 
We'll update you here.

Thanks :)

**Comment by contactjavas** [comment] 2022-02-08 14:45
Hi @AlxMedia , let me close this issue :)
If you're still experiencing it after updating Kirki, please let us know.

Thanks!

**Closed as completed by contactjavas** 2022-02-08 14:45 UTC
